package com.example.yatra

data class Destination(
    val id: Int,
    val name: String,
    val location: String,
    val description: String,
    val price: Int,
    val rating: Double,
    val temp: Int,
    val humidity: Int,
    val wind: Int,
    val altitude: String,
    val emoji: String,
    val imageUrl: Any,
    val distanceKm: Int
)

val destinations = listOf(
    Destination(
        id = 1,
        name = "Shimla",
        location = "Himachal Pradesh",
        description = "Shimla, the capital of Himachal Pradesh, is a beautiful hill station known for its colonial architecture, the Ridge, and the Mall Road.",
        price = 8999,
        rating = 4.8,
        temp = 12,
        humidity = 65,
        wind = 10,
        altitude = "2,276m",
        emoji = "❄️",
        imageUrl = R.drawable.shimla,
        distanceKm = 825
    ),
    Destination(
        id = 2,
        name = "Manali",
        location = "Himachal Pradesh",
        description = "Manali is a high-altitude Himalayan resort town known as a backpacking center and honeymoon destination.",
        price = 9500,
        rating = 4.7,
        temp = 8,
        humidity = 70,
        wind = 12,
        altitude = "2,050m",
        emoji = "🏔️",
        imageUrl = "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=1000&auto=format&fit=crop",
        distanceKm = 1000
    ),
    Destination(
        id = 3,
        name = "Banaras",
        location = "Uttar Pradesh",
        description = "Varanasi, also known as Banaras, is the spiritual capital of India, famous for its ghats along the holy River Ganges and ancient traditions.",
        price = 5500,
        rating = 4.9,
        temp = 28,
        humidity = 55,
        wind = 8,
        altitude = "81m",
        emoji = "🪔",
        imageUrl = R.drawable.banaras,
        distanceKm = 320
    ),
    Destination(
        id = 4,
        name = "Vrindavan",
        location = "Uttar Pradesh",
        description = "Vrindavan is a holy town in Uttar Pradesh, associated with the childhood of Lord Krishna. It is home to thousands of magnificent temples.",
        price = 4500,
        rating = 4.8,
        temp = 26,
        humidity = 60,
        wind = 7,
        altitude = "170m",
        emoji = "🌸",
        imageUrl = R.drawable.vrindavan,
        distanceKm = 430
    ),
    Destination(
        id = 5,
        name = "Tungnath",
        location = "Uttarakhand",
        description = "Tungnath is the highest Shiva temple in the world. It's a popular trekking destination offering 360-degree views of the Himalayas.",
        price = 7200,
        rating = 4.9,
        temp = 5,
        humidity = 75,
        wind = 15,
        altitude = "3,680m",
        emoji = "🚩",
        imageUrl = R.drawable.tungnath,
        distanceKm = 920
    ),
    Destination(
        id = 6,
        name = "Nainital",
        location = "Uttarakhand",
        description = "Nainital is a charming Himalayan resort town built around a mango-shaped lake, known for its pleasant climate and scenic beauty.",
        price = 6800,
        rating = 4.6,
        temp = 16,
        humidity = 62,
        wind = 9,
        altitude = "2,084m",
        emoji = "⛵",
        imageUrl = "https://images.unsplash.com/photo-1610715936287-6c2ad208cdbf?q=80&w=1000&auto=format&fit=crop",
        distanceKm = 310
    ),
    Destination(
        id = 7,
        name = "Spiti Valley",
        location = "Himachal Pradesh",
        description = "Spiti Valley is a cold desert mountain valley, a land of monasteries, prayer flags, and stunning landscapes.",
        price = 12000,
        rating = 4.9,
        temp = 2,
        humidity = 40,
        wind = 20,
        altitude = "3,800m",
        emoji = "🏜️",
        imageUrl = R.drawable.spitivalley,
        distanceKm = 1120
    ),
    Destination(
        id = 8,
        name = "Munnar",
        location = "Kerala",
        description = "Munnar is a town in the Western Ghats mountain range, surrounded by rolling hills dotted with tea plantations.",
        price = 9800,
        rating = 4.7,
        temp = 19,
        humidity = 80,
        wind = 6,
        altitude = "1,532m",
        emoji = "🍃",
        imageUrl = "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?q=80&w=1000&auto=format&fit=crop",
        distanceKm = 2150
    )
)
